# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: db-deployment
#   labels:
#     app: myapp
#     type: database
# spec:
#   template:
#     metadata:
#       name: db-pod
#       labels:
#         app: myapp
#         type: mongo-db
#     spec:
#       containers:
#         - name: mysql-container
#           image: mysql:5.7
#           env:
#           - name: MYSQL_ALLOW_EMPTY_PASSWORD
#             value: "yes"
#           ports:
#             - containerPort: 3306
#           resources:
#             limits:
#               memory: "128Mi"
#               cpu: "500m"
#   replicas: 1
#   selector:
#     matchLabels:
#       app: myapp
#       type: mongo-db
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: mongo
# spec:
#   type: ClusterIP
#   selector:
#     app: myapp
#     type: mongo-db
#   ports:
#   - port: 8018
#     targetPort: 3306
# ---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: myapp
    type: webserver
spec:
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx
        type: webserver
    spec:
      containers:
        - name: nginx-container
          image: nginx
          
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      type: webserver