
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: myapp
    type: webserver
spec:
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx
        type: webserver
    spec:
      containers:
        - name: nginx-container
          image: nginx
          
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      type: webserver